# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a56404e8da8ff18845d1bf3eca039b805a6d843937da8be60e957b5d46d68d2452b072a1d18fb91c9f2492731ed0f0ae7531d7a6297e91a1191afe935c7f5162

test:
  secret_key_base: d0bd773d82c448211243ed218d51311139d308a3ec6ff583fca0f86820aaf5f255ab4f9b3f5071b212b288a164e77d35f6ede21f4a525afe29a8cf53429fddcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
